version: "3"

services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  app:
    build: .
    restart: always
    working_dir: /home/node/app
    command: npm run init
    environment:
      - MONGO_URL=mongodb://db:27017/sia
    ports:
      - "3000:3000"
    volumes:
      - ./package.json:/home/node/app/package.json
    links:
      - db
