version: "3"

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"

    volumes:
      - .:/usr/app
      - /usr/app/node_modules
