version: "3"

networks:
  default:
    external: false
  web:
    external: true
      
services:
  db:
    image: mongo:latest
    restart: always
    networks: 
      - default
    ports:
      - "27017:27017"
    labels:
      - traefik.enable=false
  app:
    build: .
    restart: always
    working_dir: /home/node/app
    command: npm run prod
    environment:
      - MONGO_URL=mongodb://db:27017/sia
    labels:
      - traefik.backend=app
      - traefik.frontend.rule=Host:sia.api.uname.group
      - traefik.docker.network=web
      - traefik.port=3000
    networks:
      - default
      - web
    ports:
      - "3000:3000"
    volumes:
      - ./package.json:/home/node/app/package.json
      - ./src:/home/node/app/src
    links:
      - db
    depends_on:
      - db
