version: "3"

networks:
  default:
    external: false
  web:
    external: true
      
services:
  db:
    image: mongo:latest
    restart: always
    networks:
      - default
    ports:
      - "27017"
    labels:
      - traefik.enable=false
  app:
    build: .
    restart: always
    working_dir: /home/node/app
    command: npm run prod
    environment:
      - MONGO_URL=mongodb://db:27017/sia
    networks:
        - default
        - web
    ports:
      - "3000"
    volumes:
      - ./package.json:/home/node/app/package.json
      - ./src:/home/node/app/src
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sia_app_1.rule=Host(`sia.api.uname.group`)"
      - "traefik.http.routers.sia_app_1.entrypoints=web"
      - "traefik.http.services.sia_app_1.loadbalancer.server.port=3000"
    links:
      - db
    depends_on:
      - db
