version: "3"

services:
  db:
    container_name: "sia_db"
    image: mongo:latest
    ports:
      - "27017:27017"
  app:
    container_name: "sia_app"
    build: .
    command: npm start
    ports:
      - "3000:3000"

    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
