


export const afrigisStationSeed = [
    {
        "stationCod": 68830,
        "name": "GEORGE CLIMATE AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "GEORGE CLIMATE AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.008,
        "lng": 22.3817
    },
    {
        "stationCod": 68921,
        "name": "STRUISBAAI",
        "status": "enabled",
        "type": "automatic",
        "city": "STRUISBAAI",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.8002,
        "lng": 20.0569
    },
    {
        "stationCod": 68924,
        "name": "OVERBERG - AAWS",
        "status": "enabled",
        "type": "automatic",
        "city": "OVERBERG - AAWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.5516,
        "lng": 20.2521
    },
    {
        "stationCod": 68916,
        "name": "CAPE POINT",
        "status": "enabled",
        "type": "automatic",
        "city": "CAPE POINT",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.3532,
        "lng": 18.4894
    },
    {
        "stationCod": 68911,
        "name": "STRAND",
        "status": "enabled",
        "type": "automatic",
        "city": "STRAND",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.1411,
        "lng": 18.8488
    },
    {
        "stationCod": 68925,
        "name": "GRABOUW",
        "status": "enabled",
        "type": "automatic",
        "city": "GRABOUW",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.1525,
        "lng": 19.0298
    },
    {
        "stationCod": 68918,
        "name": "HERMANUS",
        "status": "enabled",
        "type": "automatic",
        "city": "HERMANUS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.4324,
        "lng": 19.2246
    },
    {
        "stationCod": 68923,
        "name": "TYGERHOEK",
        "status": "enabled",
        "type": "automatic",
        "city": "TYGERHOEK",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.1497,
        "lng": 19.9031
    },
    {
        "stationCod": 68922,
        "name": "SWELLENDAM",
        "status": "enabled",
        "type": "automatic",
        "city": "SWELLENDAM",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.0215,
        "lng": 20.4367
    },
    {
        "stationCod": 68927,
        "name": "STILBAAI",
        "status": "enabled",
        "type": "automatic",
        "city": "STILBAAI",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.369,
        "lng": 21.3913
    },
    {
        "stationCod": 68928,
        "name": "MOSSEL BAY",
        "status": "enabled",
        "type": "automatic",
        "city": "MOSSEL BAY",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.1894,
        "lng": 22.1318
    },
    {
        "stationCod": 68935,
        "name": "KNYSNA",
        "status": "enabled",
        "type": "automatic",
        "city": "KNYSNA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.049,
        "lng": 23.0815
    },
    {
        "stationCod": 68931,
        "name": "PLETTENBERGBAAI",
        "status": "enabled",
        "type": "automatic",
        "city": "PLETTENBERGBAAI",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.0896,
        "lng": 23.3259
    },
    {
        "stationCod": 68933,
        "name": "TSITSIKAMMA",
        "status": "enabled",
        "type": "automatic",
        "city": "TSITSIKAMMA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.0229,
        "lng": 23.8986
    },
    {
        "stationCod": 68939,
        "name": "CAPE ST FRANCIS",
        "status": "enabled",
        "type": "automatic",
        "city": "CAPE ST FRANCIS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -34.2122,
        "lng": 24.8357
    },
    {
        "stationCod": 68813,
        "name": "ROBBENEILAND",
        "status": "enabled",
        "type": "automatic",
        "city": "ROBBENEILAND",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.7989,
        "lng": 18.3744
    },
    {
        "stationCod": 68819,
        "name": "MOLTENO RESERVOIR",
        "status": "enabled",
        "type": "automatic",
        "city": "MOLTENO RESERVOIR",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.9377,
        "lng": 18.4109
    },
    {
        "stationCod": 68812,
        "name": "KIRSTENBOSCH",
        "status": "enabled",
        "type": "automatic",
        "city": "KIRSTENBOSCH",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.986,
        "lng": 18.4307
    },
    {
        "stationCod": 68817,
        "name": "CAPE TOWN - ROYAL YACHT CLUB",
        "status": "enabled",
        "type": "automatic",
        "city": "CAPE TOWN - ROYAL YACHT CLUB",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.9206,
        "lng": 18.443
    },
    {
        "stationCod": 68809,
        "name": "ATLANTIS",
        "status": "enabled",
        "type": "automatic",
        "city": "ATLANTIS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.6077,
        "lng": 18.4833
    },
    {
        "stationCod": 68820,
        "name": "S A ASTRONOMICAL OBSERVATORY",
        "status": "enabled",
        "type": "automatic",
        "city": "S A ASTRONOMICAL OBSERVATORY",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.9336,
        "lng": 18.4775
    },
    {
        "stationCod": 68822,
        "name": "JONKERSHOEK",
        "status": "enabled",
        "type": "automatic",
        "city": "JONKERSHOEK",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.9679,
        "lng": 18.9224
    },
    {
        "stationCod": 68713,
        "name": "PAARL",
        "status": "enabled",
        "type": "automatic",
        "city": "PAARL",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.7219,
        "lng": 18.972
    },
    {
        "stationCod": 68810,
        "name": "WELLINGTON",
        "status": "enabled",
        "type": "automatic",
        "city": "WELLINGTON",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.6509,
        "lng": 19.0057
    },
    {
        "stationCod": 68821,
        "name": "WORCESTER-AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "WORCESTER-AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.6639,
        "lng": 19.4187
    },
    {
        "stationCod": 68829,
        "name": "GEORGE WITFONTEIN",
        "status": "enabled",
        "type": "automatic",
        "city": "GEORGE WITFONTEIN",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.9353,
        "lng": 22.4269
    },
    {
        "stationCod": 68833,
        "name": "JOUBERTINA SCHOOL AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "JOUBERTINA SCHOOL AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.8247,
        "lng": 23.8606
    },
    {
        "stationCod": 68835,
        "name": "PATENSIE",
        "status": "enabled",
        "type": "automatic",
        "city": "PATENSIE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.7653,
        "lng": 24.8233
    },
    {
        "stationCod": 68839,
        "name": "UITENHAGE",
        "status": "enabled",
        "type": "automatic",
        "city": "UITENHAGE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.7141,
        "lng": 25.4352
    },
    {
        "stationCod": 68846,
        "name": "PORT ELIZABETH - CHATTY HYBRID AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "PORT ELIZABETH - CHATTY HYBRID AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.8524,
        "lng": 25.5357
    },
    {
        "stationCod": 68848,
        "name": "PORT ELIZABETH - FETTES ROAD HYBRID",
        "status": "enabled",
        "type": "automatic",
        "city": "PORT ELIZABETH - FETTES ROAD HYBRID",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.9425,
        "lng": 25.6023
    },
    {
        "stationCod": 68844,
        "name": "PORT ELIZABETH AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "PORT ELIZABETH AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.9827,
        "lng": 25.6138
    },
    {
        "stationCod": 68940,
        "name": "PORT ELIZABETH - SHARK ROCK PIER HYBRID",
        "status": "enabled",
        "type": "automatic",
        "city": "PORT ELIZABETH - SHARK ROCK PIER HYBRID",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.9796,
        "lng": 25.6598
    },
    {
        "stationCod": 68941,
        "name": "PORT OF NGQURA HYBRID",
        "status": "enabled",
        "type": "automatic",
        "city": "PORT OF NGQURA HYBRID",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.809,
        "lng": 25.6905
    },
    {
        "stationCod": 68837,
        "name": "NGQURA - COEGA",
        "status": "enabled",
        "type": "automatic",
        "city": "NGQURA - COEGA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.8051,
        "lng": 25.6695
    },
    {
        "stationCod": 68942,
        "name": "PORT ELIZABETH - COLCHESTER HYBRID",
        "status": "enabled",
        "type": "automatic",
        "city": "PORT ELIZABETH - COLCHESTER HYBRID",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.6851,
        "lng": 25.8239
    },
    {
        "stationCod": 68843,
        "name": "PORT ALFRED - AIRPORT",
        "status": "enabled",
        "type": "automatic",
        "city": "PORT ALFRED - AIRPORT",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.5595,
        "lng": 26.8809
    },
    {
        "stationCod": 68811,
        "name": "GEELBEK",
        "status": "enabled",
        "type": "automatic",
        "city": "GEELBEK",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.1964,
        "lng": 18.1241
    },
    {
        "stationCod": 68716,
        "name": "LANGGEWENS",
        "status": "enabled",
        "type": "automatic",
        "city": "LANGGEWENS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.2763,
        "lng": 18.7051
    },
    {
        "stationCod": 68715,
        "name": "MALMESBURY",
        "status": "enabled",
        "type": "automatic",
        "city": "MALMESBURY",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.4725,
        "lng": 18.7183
    },
    {
        "stationCod": 68717,
        "name": "PORTERVILLE",
        "status": "enabled",
        "type": "automatic",
        "city": "PORTERVILLE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.0128,
        "lng": 18.9771
    },
    {
        "stationCod": 68815,
        "name": "CERES AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "CERES AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.3848,
        "lng": 19.3212
    },
    {
        "stationCod": 68723,
        "name": "LAINGSBURG",
        "status": "enabled",
        "type": "automatic",
        "city": "LAINGSBURG",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.1908,
        "lng": 20.8626
    },
    {
        "stationCod": 68825,
        "name": "LADISMITH",
        "status": "enabled",
        "type": "automatic",
        "city": "LADISMITH",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.5006,
        "lng": 21.2653
    },
    {
        "stationCod": 68823,
        "name": "PRINS ALBERT - SWARTRIVIER",
        "status": "enabled",
        "type": "automatic",
        "city": "PRINS ALBERT - SWARTRIVIER",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.1734,
        "lng": 22.0293
    },
    {
        "stationCod": 68840,
        "name": "SOMERSET EAST",
        "status": "enabled",
        "type": "automatic",
        "city": "SOMERSET EAST",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.0497,
        "lng": 25.7193
    },
    {
        "stationCod": 68841,
        "name": "ADDO ELEPHANT PARK",
        "status": "enabled",
        "type": "automatic",
        "city": "ADDO ELEPHANT PARK",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.4421,
        "lng": 25.7485
    },
    {
        "stationCod": 68849,
        "name": "GRAHAMSTOWN",
        "status": "enabled",
        "type": "automatic",
        "city": "GRAHAMSTOWN",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.2907,
        "lng": 26.5026
    },
    {
        "stationCod": 68695,
        "name": "LANGEBAANWEG - AAWS",
        "status": "enabled",
        "type": "automatic",
        "city": "LANGEBAANWEG - AAWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -32.9788,
        "lng": 18.1641
    },
    {
        "stationCod": 68714,
        "name": "LANGEBAANWEG AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "LANGEBAANWEG AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -32.9725,
        "lng": 18.1578
    },
    {
        "stationCod": 68719,
        "name": "EXCELSIOR CERES",
        "status": "enabled",
        "type": "automatic",
        "city": "EXCELSIOR CERES",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -32.9636,
        "lng": 19.4308
    },
    {
        "stationCod": 68747,
        "name": "FORT BEAUFORT",
        "status": "enabled",
        "type": "automatic",
        "city": "FORT BEAUFORT",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -32.7881,
        "lng": 26.6293
    },
    {
        "stationCod": 68613,
        "name": "LAMBERTSBAAI NORTIER",
        "status": "enabled",
        "type": "automatic",
        "city": "LAMBERTSBAAI NORTIER",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -32.0351,
        "lng": 18.3326
    },
    {
        "stationCod": 68999,
        "name": "CT-AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "CT-AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.9789,
        "lng": 18.6
    },
    {
        "stationCod": 68710,
        "name": "REDELINGSHUYS-AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "REDELINGSHUYS-AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -32.4814,
        "lng": 18.537
    },
    {
        "stationCod": 68711,
        "name": "CLANWILLIAM",
        "status": "enabled",
        "type": "automatic",
        "city": "CLANWILLIAM",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -32.1768,
        "lng": 18.888
    },
    {
        "stationCod": 68727,
        "name": "BEAUFORT-WES",
        "status": "enabled",
        "type": "automatic",
        "city": "BEAUFORT-WES",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -32.3476,
        "lng": 22.5731
    },
    {
        "stationCod": 68858,
        "name": "EAST LONDON WO",
        "status": "enabled",
        "type": "automatic",
        "city": "EAST LONDON WO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.0357,
        "lng": 27.8161
    },
    {
        "stationCod": 68744,
        "name": "CRADOCK-MUN",
        "status": "enabled",
        "type": "automatic",
        "city": "CRADOCK-MUN",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -32.1675,
        "lng": 25.6253
    },
    {
        "stationCod": 68668,
        "name": "UMTHATHA WO",
        "status": "enabled",
        "type": "automatic",
        "city": "UMTHATHA WO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -31.5497,
        "lng": 28.6739
    },
    {
        "stationCod": 68677,
        "name": "COFFEE BAY",
        "status": "enabled",
        "type": "automatic",
        "city": "COFFEE BAY",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -31.9653,
        "lng": 29.1346
    },
    {
        "stationCod": 68674,
        "name": "PORT ST. JOHNS",
        "status": "enabled",
        "type": "automatic",
        "city": "PORT ST. JOHNS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -31.6534,
        "lng": 29.5077
    },
    {
        "stationCod": 68618,
        "name": "CALVINIA WO",
        "status": "enabled",
        "type": "automatic",
        "city": "CALVINIA WO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -31.4819,
        "lng": 19.7617
    },
    {
        "stationCod": 68633,
        "name": "NOUPOORT",
        "status": "enabled",
        "type": "automatic",
        "city": "NOUPOORT",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -31.1863,
        "lng": 24.9603
    },
    {
        "stationCod": 68587,
        "name": "PORT EDWARD",
        "status": "enabled",
        "type": "automatic",
        "city": "PORT EDWARD",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -31.0621,
        "lng": 30.2213
    },
    {
        "stationCod": 68516,
        "name": "GARIES AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "GARIES AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -30.5611,
        "lng": 17.9874
    },
    {
        "stationCod": 68538,
        "name": "DE AAR WO",
        "status": "enabled",
        "type": "automatic",
        "city": "DE AAR WO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -30.6651,
        "lng": 23.9927
    },
    {
        "stationCod": 68543,
        "name": "GARIEP DAM",
        "status": "enabled",
        "type": "automatic",
        "city": "GARIEP DAM",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -30.5621,
        "lng": 25.5278
    },
    {
        "stationCod": 68579,
        "name": "PADDOCK",
        "status": "enabled",
        "type": "automatic",
        "city": "PADDOCK",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -30.7544,
        "lng": 30.2577
    },
    {
        "stationCod": 68591,
        "name": "MARGATE",
        "status": "enabled",
        "type": "automatic",
        "city": "MARGATE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -30.8588,
        "lng": 30.3433
    },
    {
        "stationCod": 68513,
        "name": "KOINGNAAS",
        "status": "enabled",
        "type": "automatic",
        "city": "KOINGNAAS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -30.1955,
        "lng": 17.2903
    },
    {
        "stationCod": 68523,
        "name": "BRANDVLEI",
        "status": "enabled",
        "type": "automatic",
        "city": "BRANDVLEI",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -30.4647,
        "lng": 20.4783
    },
    {
        "stationCod": 68575,
        "name": "IXOPO",
        "status": "enabled",
        "type": "automatic",
        "city": "IXOPO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -30.1525,
        "lng": 30.0747
    },
    {
        "stationCod": 68512,
        "name": "SPRINGBOK WO",
        "status": "enabled",
        "type": "automatic",
        "city": "SPRINGBOK WO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.6694,
        "lng": 17.8788
    },
    {
        "stationCod": 68527,
        "name": "PRIESKA",
        "status": "enabled",
        "type": "automatic",
        "city": "PRIESKA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.6701,
        "lng": 22.7401
    },
    {
        "stationCod": 68439,
        "name": "ORANIA AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "ORANIA AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.8185,
        "lng": 24.4112
    },
    {
        "stationCod": 68573,
        "name": "EMERALD DALE AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "EMERALD DALE AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.9403,
        "lng": 29.9597
    },
    {
        "stationCod": 68581,
        "name": "PIETERMARITZBURG",
        "status": "enabled",
        "type": "automatic",
        "city": "PIETERMARITZBURG",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.6278,
        "lng": 30.4029
    },
    {
        "stationCod": 68582,
        "name": "ORIBI AIRPORT",
        "status": "enabled",
        "type": "automatic",
        "city": "ORIBI AIRPORT",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.6478,
        "lng": 30.3995
    },
    {
        "stationCod": 68588,
        "name": "DURBAN SOUTH ATHLONE PARK",
        "status": "enabled",
        "type": "automatic",
        "city": "DURBAN SOUTH ATHLONE PARK",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -30.0133,
        "lng": 30.9264
    },
    {
        "stationCod": 68583,
        "name": "MOUNT EDGECOMBE",
        "status": "enabled",
        "type": "automatic",
        "city": "MOUNT EDGECOMBE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.7068,
        "lng": 31.046
    },
    {
        "stationCod": 68593,
        "name": "VIRGINIA",
        "status": "enabled",
        "type": "automatic",
        "city": "VIRGINIA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.7729,
        "lng": 31.0555
    },
    {
        "stationCod": 68594,
        "name": "KING SHAKA AWOS",
        "status": "enabled",
        "type": "automatic",
        "city": "KING SHAKA AWOS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.6019,
        "lng": 31.1295
    },
    {
        "stationCod": 68408,
        "name": "PORT NOLLOTH",
        "status": "enabled",
        "type": "automatic",
        "city": "PORT NOLLOTH",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.25,
        "lng": 16.8685
    },
    {
        "stationCod": 68589,
        "name": "GIANTS CASTLE AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "GIANTS CASTLE AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.2649,
        "lng": 29.5223
    },
    {
        "stationCod": 68485,
        "name": "MOOI RIVER",
        "status": "enabled",
        "type": "automatic",
        "city": "MOOI RIVER",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.218,
        "lng": 30.0025
    },
    {
        "stationCod": 68577,
        "name": "KOKSTAD",
        "status": "enabled",
        "type": "automatic",
        "city": "KOKSTAD",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -30.5028,
        "lng": 29.3942
    },
    {
        "stationCod": 68487,
        "name": "GREYTOWN",
        "status": "enabled",
        "type": "automatic",
        "city": "GREYTOWN",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.0832,
        "lng": 30.6034
    },
    {
        "stationCod": 68494,
        "name": "MANDINI",
        "status": "enabled",
        "type": "automatic",
        "city": "MANDINI",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.1582,
        "lng": 31.4023
    },
    {
        "stationCod": 68403,
        "name": "ALEXANDERBAAI",
        "status": "enabled",
        "type": "automatic",
        "city": "ALEXANDERBAAI",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.57,
        "lng": 16.5287
    },
    {
        "stationCod": 68411,
        "name": "VIOOLSDRIF - AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "VIOOLSDRIF - AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.7694,
        "lng": 17.6234
    },
    {
        "stationCod": 68754,
        "name": "DOHNE - AGR",
        "status": "enabled",
        "type": "automatic",
        "city": "DOHNE - AGR",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -32.5276,
        "lng": 27.4606
    },
    {
        "stationCod": 68438,
        "name": "KIMBERLEY WO",
        "status": "enabled",
        "type": "automatic",
        "city": "KIMBERLEY WO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.8061,
        "lng": 24.7698
    },
    {
        "stationCod": 68449,
        "name": "FICKSBURG",
        "status": "enabled",
        "type": "automatic",
        "city": "FICKSBURG",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.8272,
        "lng": 27.9041
    },
    {
        "stationCod": 68479,
        "name": "LADYSMITH",
        "status": "enabled",
        "type": "automatic",
        "city": "LADYSMITH",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.5755,
        "lng": 29.7503
    },
    {
        "stationCod": 68752,
        "name": "BISHO",
        "status": "enabled",
        "type": "automatic",
        "city": "BISHO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -32.8945,
        "lng": 27.2868
    },
    {
        "stationCod": 68497,
        "name": "MTUNZINI",
        "status": "enabled",
        "type": "automatic",
        "city": "MTUNZINI",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.9474,
        "lng": 31.7079
    },
    {
        "stationCod": 68490,
        "name": "UNIVERSITY OF ZULULAND",
        "status": "enabled",
        "type": "automatic",
        "city": "UNIVERSITY OF ZULULAND",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.8517,
        "lng": 31.853
    },
    {
        "stationCod": 68495,
        "name": "RICHARDS BAY AIRPORT",
        "status": "enabled",
        "type": "automatic",
        "city": "RICHARDS BAY AIRPORT",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.7378,
        "lng": 32.0934
    },
    {
        "stationCod": 68647,
        "name": "QUEENSTOWN",
        "status": "enabled",
        "type": "automatic",
        "city": "QUEENSTOWN",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -31.9178,
        "lng": 26.8781
    },
    {
        "stationCod": 68424,
        "name": "UPINGTON WO",
        "status": "enabled",
        "type": "automatic",
        "city": "UPINGTON WO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.4111,
        "lng": 21.2641
    },
    {
        "stationCod": 68429,
        "name": "POSTMASBURG",
        "status": "enabled",
        "type": "automatic",
        "city": "POSTMASBURG",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.3454,
        "lng": 23.079
    },
    {
        "stationCod": 68461,
        "name": "BETHLEHEM WO",
        "status": "enabled",
        "type": "automatic",
        "city": "BETHLEHEM WO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.2496,
        "lng": 28.3343
    },
    {
        "stationCod": 68471,
        "name": "VAN REENEN",
        "status": "enabled",
        "type": "automatic",
        "city": "VAN REENEN",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.3789,
        "lng": 29.3853
    },
    {
        "stationCod": 68425,
        "name": "AUGRABIES FALLS",
        "status": "enabled",
        "type": "automatic",
        "city": "AUGRABIES FALLS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.595,
        "lng": 20.3401
    },
    {
        "stationCod": 68488,
        "name": "BABANANGO",
        "status": "enabled",
        "type": "automatic",
        "city": "BABANANGO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.3644,
        "lng": 31.2065
    },
    {
        "stationCod": 68857,
        "name": "EAST LONDON WO AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "EAST LONDON WO AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.0225,
        "lng": 27.8199
    },
    {
        "stationCod": 68493,
        "name": "ULUNDI",
        "status": "enabled",
        "type": "automatic",
        "city": "ULUNDI",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.3126,
        "lng": 31.4206
    },
    {
        "stationCod": 68492,
        "name": "RIVERVIEW",
        "status": "enabled",
        "type": "automatic",
        "city": "RIVERVIEW",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.444,
        "lng": 32.1821
    },
    {
        "stationCod": 68491,
        "name": "CHARTERS CREEK",
        "status": "enabled",
        "type": "automatic",
        "city": "CHARTERS CREEK",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.1978,
        "lng": 32.4142
    },
    {
        "stationCod": 68331,
        "name": "KATHU",
        "status": "enabled",
        "type": "automatic",
        "city": "KATHU",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -27.6703,
        "lng": 23.0063
    },
    {
        "stationCod": 68648,
        "name": "BUFFELSFONTEIN",
        "status": "enabled",
        "type": "automatic",
        "city": "BUFFELSFONTEIN",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -31.3694,
        "lng": 26.6969
    },
    {
        "stationCod": 68242,
        "name": "MAFIKENG WO",
        "status": "enabled",
        "type": "automatic",
        "city": "MAFIKENG WO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.8037,
        "lng": 25.5428
    },
    {
        "stationCod": 68335,
        "name": "TAUNG",
        "status": "enabled",
        "type": "automatic",
        "city": "TAUNG",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -27.5452,
        "lng": 24.7687
    },
    {
        "stationCod": 68336,
        "name": "VAALHARTS AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "VAALHARTS AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -27.9575,
        "lng": 24.8406
    },
    {
        "stationCod": 68649,
        "name": "JAMESTOWN",
        "status": "enabled",
        "type": "automatic",
        "city": "JAMESTOWN",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -31.121,
        "lng": 26.8098
    },
    {
        "stationCod": 68355,
        "name": "KROONSTAD",
        "status": "enabled",
        "type": "automatic",
        "city": "KROONSTAD",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -27.6665,
        "lng": 27.3136
    },
    {
        "stationCod": 68376,
        "name": "WARDEN - HERITAGE",
        "status": "enabled",
        "type": "automatic",
        "city": "WARDEN - HERITAGE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -27.9611,
        "lng": 29.0594
    },
    {
        "stationCod": 68850,
        "name": "PORT ELIZABETH - MOTHERWELL HYBRID",
        "status": "enabled",
        "type": "automatic",
        "city": "PORT ELIZABETH - MOTHERWELL HYBRID",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.8032,
        "lng": 25.6209
    },
    {
        "stationCod": 68651,
        "name": "ELLIOT",
        "status": "enabled",
        "type": "automatic",
        "city": "ELLIOT",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -31.3363,
        "lng": 27.8404
    },
    {
        "stationCod": 68333,
        "name": "KURUMAN",
        "status": "enabled",
        "type": "automatic",
        "city": "KURUMAN",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -27.4331,
        "lng": 23.4474
    },
    {
        "stationCod": 68363,
        "name": "SPRINGS",
        "status": "enabled",
        "type": "automatic",
        "city": "SPRINGS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -26.2395,
        "lng": 28.4351
    },
    {
        "stationCod": 68375,
        "name": "VREDE",
        "status": "enabled",
        "type": "automatic",
        "city": "VREDE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -27.4228,
        "lng": 29.1695
    },
    {
        "stationCod": 68253,
        "name": "THABAZIMBI",
        "status": "enabled",
        "type": "automatic",
        "city": "THABAZIMBI",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -24.5799,
        "lng": 27.4134
    },
    {
        "stationCod": 68481,
        "name": "PONGOLA",
        "status": "enabled",
        "type": "automatic",
        "city": "PONGOLA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -27.4139,
        "lng": 31.5906
    },
    {
        "stationCod": 68397,
        "name": "MBAZWANA AIRFIELD",
        "status": "enabled",
        "type": "automatic",
        "city": "MBAZWANA AIRFIELD",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -27.4775,
        "lng": 32.5983
    },
    {
        "stationCod": 68329,
        "name": "VAN ZYLSRUS",
        "status": "enabled",
        "type": "automatic",
        "city": "VAN ZYLSRUS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -26.8774,
        "lng": 22.0499
    },
    {
        "stationCod": 68347,
        "name": "KLERKSDORP",
        "status": "enabled",
        "type": "automatic",
        "city": "KLERKSDORP",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -26.8981,
        "lng": 26.6209
    },
    {
        "stationCod": 68350,
        "name": "POTCHEFSTROOM",
        "status": "enabled",
        "type": "automatic",
        "city": "POTCHEFSTROOM",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -26.7359,
        "lng": 27.0755
    },
    {
        "stationCod": 68341,
        "name": "LICHTENBURG",
        "status": "enabled",
        "type": "automatic",
        "city": "LICHTENBURG",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -26.133,
        "lng": 26.1644
    },
    {
        "stationCod": 68349,
        "name": "VENTERSDORP",
        "status": "enabled",
        "type": "automatic",
        "city": "VENTERSDORP",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -26.3123,
        "lng": 26.8138
    },
    {
        "stationCod": 68351,
        "name": "ZUURBEKOM AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "ZUURBEKOM AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -26.3008,
        "lng": 27.8136
    },
    {
        "stationCod": 68352,
        "name": "ROODEPOORT - KLOOFENDAL",
        "status": "enabled",
        "type": "automatic",
        "city": "ROODEPOORT - KLOOFENDAL",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -26.1308,
        "lng": 27.8799
    },
    {
        "stationCod": 68361,
        "name": "JHB BOT TUINE",
        "status": "enabled",
        "type": "automatic",
        "city": "JHB BOT TUINE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -26.1566,
        "lng": 27.9991
    },
    {
        "stationCod": 68267,
        "name": "ERMELO WO",
        "status": "enabled",
        "type": "automatic",
        "city": "ERMELO WO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -26.4977,
        "lng": 29.9838
    },
    {
        "stationCod": 68237,
        "name": "TOSCA",
        "status": "enabled",
        "type": "automatic",
        "city": "TOSCA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.878,
        "lng": 23.966
    },
    {
        "stationCod": 68255,
        "name": "RUSTENBURG",
        "status": "enabled",
        "type": "automatic",
        "city": "RUSTENBURG",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.6607,
        "lng": 27.2322
    },
    {
        "stationCod": 68254,
        "name": "BUFFELSPOORT II AGR",
        "status": "enabled",
        "type": "automatic",
        "city": "BUFFELSPOORT II AGR",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.7539,
        "lng": 27.4828
    },
    {
        "stationCod": 68258,
        "name": "HARTEBEESPOORT DAM",
        "status": "enabled",
        "type": "automatic",
        "city": "HARTEBEESPOORT DAM",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.7486,
        "lng": 27.8325
    },
    {
        "stationCod": 68269,
        "name": "PRETORIA UNISA",
        "status": "enabled",
        "type": "automatic",
        "city": "PRETORIA UNISA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.7663,
        "lng": 28.2005
    },
    {
        "stationCod": 68266,
        "name": "WONDERBOOM AIRPORT",
        "status": "enabled",
        "type": "automatic",
        "city": "WONDERBOOM AIRPORT",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.6631,
        "lng": 28.2166
    },
    {
        "stationCod": 68546,
        "name": "ALIWAL-NORTH PLAATKOP",
        "status": "enabled",
        "type": "automatic",
        "city": "ALIWAL-NORTH PLAATKOP",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -30.8029,
        "lng": 26.8834
    },
    {
        "stationCod": 68553,
        "name": "LADY GREY - IDEAL",
        "status": "enabled",
        "type": "automatic",
        "city": "LADY GREY - IDEAL",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -30.8864,
        "lng": 27.2344
    },
    {
        "stationCod": 68264,
        "name": "WATERKLOOF AIR FORCE BASE",
        "status": "enabled",
        "type": "automatic",
        "city": "WATERKLOOF AIR FORCE BASE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.8277,
        "lng": 28.2235
    },
    {
        "stationCod": 68263,
        "name": "IRENE WO",
        "status": "enabled",
        "type": "automatic",
        "city": "IRENE WO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.9105,
        "lng": 28.2106
    },
    {
        "stationCod": 68260,
        "name": "PRETORIA UNIVERSITY PROEFPLAAS",
        "status": "enabled",
        "type": "automatic",
        "city": "PRETORIA UNIVERSITY PROEFPLAAS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.752,
        "lng": 28.2585
    },
    {
        "stationCod": 68549,
        "name": "WEPENER",
        "status": "enabled",
        "type": "automatic",
        "city": "WEPENER",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.9157,
        "lng": 26.847
    },
    {
        "stationCod": 68542,
        "name": "KNELLPOORTDAM",
        "status": "enabled",
        "type": "automatic",
        "city": "KNELLPOORTDAM",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.7861,
        "lng": 26.9031
    },
    {
        "stationCod": 68443,
        "name": "BLOEMFONTEIN - STAD",
        "status": "enabled",
        "type": "automatic",
        "city": "BLOEMFONTEIN - STAD",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.1204,
        "lng": 26.1874
    },
    {
        "stationCod": 68274,
        "name": "BRONKHORSTSPRUIT AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "BRONKHORSTSPRUIT AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.8087,
        "lng": 28.7386
    },
    {
        "stationCod": 68273,
        "name": "WITBANK",
        "status": "enabled",
        "type": "automatic",
        "city": "WITBANK",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.8323,
        "lng": 29.1921
    },
    {
        "stationCod": 68541,
        "name": "FAURESMITH",
        "status": "enabled",
        "type": "automatic",
        "city": "FAURESMITH",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -29.7535,
        "lng": 25.323
    },
    {
        "stationCod": 68447,
        "name": "GLEN COLLEGE AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "GLEN COLLEGE AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -28.942,
        "lng": 26.3258
    },
    {
        "stationCod": 68297,
        "name": "KOMATIDRAAI",
        "status": "enabled",
        "type": "automatic",
        "city": "KOMATIDRAAI",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.5145,
        "lng": 31.9103
    },
    {
        "stationCod": 68248,
        "name": "MARICO",
        "status": "enabled",
        "type": "automatic",
        "city": "MARICO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.4718,
        "lng": 26.3819
    },
    {
        "stationCod": 68371,
        "name": "SECUNDA",
        "status": "enabled",
        "type": "automatic",
        "city": "SECUNDA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -26.4975,
        "lng": 29.1864
    },
    {
        "stationCod": 68249,
        "name": "LINDLEYSPOORT",
        "status": "enabled",
        "type": "automatic",
        "city": "LINDLEYSPOORT",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.5025,
        "lng": 26.6963
    },
    {
        "stationCod": 68250,
        "name": "PILANESBERG - AAWS",
        "status": "enabled",
        "type": "automatic",
        "city": "PILANESBERG - AAWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.3342,
        "lng": 27.1721
    },
    {
        "stationCod": 68387,
        "name": "VRYHEID",
        "status": "enabled",
        "type": "automatic",
        "city": "VRYHEID",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -27.7773,
        "lng": 30.7961
    },
    {
        "stationCod": 68257,
        "name": "PILANESBERG",
        "status": "enabled",
        "type": "automatic",
        "city": "PILANESBERG",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.2573,
        "lng": 27.2238
    },
    {
        "stationCod": 68272,
        "name": "OUDESTAD",
        "status": "enabled",
        "type": "automatic",
        "city": "OUDESTAD",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.1815,
        "lng": 29.339
    },
    {
        "stationCod": 68185,
        "name": "LYDENBURG",
        "status": "enabled",
        "type": "automatic",
        "city": "LYDENBURG",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.1119,
        "lng": 30.4766
    },
    {
        "stationCod": 68343,
        "name": "BLOEMHOF",
        "status": "enabled",
        "type": "automatic",
        "city": "BLOEMHOF",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -27.6511,
        "lng": 25.6219
    },
    {
        "stationCod": 68345,
        "name": "WELKOM",
        "status": "enabled",
        "type": "automatic",
        "city": "WELKOM",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -27.9947,
        "lng": 26.666
    },
    {
        "stationCod": 68261,
        "name": "BOLEPI HOUSE",
        "status": "enabled",
        "type": "automatic",
        "city": "BOLEPI HOUSE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.8094,
        "lng": 28.2564
    },
    {
        "stationCod": 68289,
        "name": "NELSPRUIT",
        "status": "enabled",
        "type": "automatic",
        "city": "NELSPRUIT",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.5031,
        "lng": 30.9116
    },
    {
        "stationCod": 68348,
        "name": "BOTHAVILLE - BALKFONTEIN",
        "status": "enabled",
        "type": "automatic",
        "city": "BOTHAVILLE - BALKFONTEIN",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -27.4058,
        "lng": 26.5044
    },
    {
        "stationCod": 68190,
        "name": "MODJADJI WATER PLANT",
        "status": "enabled",
        "type": "automatic",
        "city": "MODJADJI WATER PLANT",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -23.5894,
        "lng": 30.3533
    },
    {
        "stationCod": 68290,
        "name": "KRUGER MPUMALANGA INT. AIR.",
        "status": "enabled",
        "type": "automatic",
        "city": "KRUGER MPUMALANGA INT. AIR.",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.3877,
        "lng": 31.0995
    },
    {
        "stationCod": 68241,
        "name": "MADIKWE GAME RESERVE",
        "status": "enabled",
        "type": "automatic",
        "city": "MADIKWE GAME RESERVE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -24.6884,
        "lng": 26.1964
    },
    {
        "stationCod": 68353,
        "name": "VEREENIGING",
        "status": "enabled",
        "type": "automatic",
        "city": "VEREENIGING",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -26.5699,
        "lng": 27.9582
    },
    {
        "stationCod": 68268,
        "name": "WARMBAD TOWOOMBA",
        "status": "enabled",
        "type": "automatic",
        "city": "WARMBAD TOWOOMBA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -24.8992,
        "lng": 28.3239
    },
    {
        "stationCod": 68283,
        "name": "BOURKE'S LUCK AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "BOURKE'S LUCK AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -24.6724,
        "lng": 30.8092
    },
    {
        "stationCod": 68380,
        "name": "CAROLINA",
        "status": "enabled",
        "type": "automatic",
        "city": "CAROLINA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -26.0739,
        "lng": 30.11
    },
    {
        "stationCod": 68287,
        "name": "GRASKOP AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "GRASKOP AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -24.9351,
        "lng": 30.8391
    },
    {
        "stationCod": 68271,
        "name": "MOKOPANE",
        "status": "enabled",
        "type": "automatic",
        "city": "MOKOPANE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -24.1967,
        "lng": 29.0066
    },
    {
        "stationCod": 68291,
        "name": "HOEDSPRUIT AIR FORCE BASE",
        "status": "enabled",
        "type": "automatic",
        "city": "HOEDSPRUIT AIR FORCE BASE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -24.3526,
        "lng": 31.0493
    },
    {
        "stationCod": 68155,
        "name": "LEPHALALE",
        "status": "enabled",
        "type": "automatic",
        "city": "LEPHALALE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -23.6767,
        "lng": 27.7051
    },
    {
        "stationCod": 68285,
        "name": "BELFAST",
        "status": "enabled",
        "type": "automatic",
        "city": "BELFAST",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.6917,
        "lng": 30.0344
    },
    {
        "stationCod": 68286,
        "name": "MACHADODORP AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "MACHADODORP AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -25.7158,
        "lng": 30.2303
    },
    {
        "stationCod": 68163,
        "name": "MARKEN",
        "status": "enabled",
        "type": "automatic",
        "city": "MARKEN",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -23.5948,
        "lng": 28.3878
    },
    {
        "stationCod": 68174,
        "name": "POLOKWANE WO",
        "status": "enabled",
        "type": "automatic",
        "city": "POLOKWANE WO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -23.8576,
        "lng": 29.4517
    },
    {
        "stationCod": 68188,
        "name": "TZANEEN-WESTFALIA ESTATE",
        "status": "enabled",
        "type": "automatic",
        "city": "TZANEEN-WESTFALIA ESTATE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -23.7367,
        "lng": 30.1127
    },
    {
        "stationCod": 68193,
        "name": "PHALABORWA GATE",
        "status": "enabled",
        "type": "automatic",
        "city": "PHALABORWA GATE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -23.9445,
        "lng": 31.1658
    },
    {
        "stationCod": 68179,
        "name": "MAKHADO AIR FORCE BASE",
        "status": "enabled",
        "type": "automatic",
        "city": "MAKHADO AIR FORCE BASE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -23.1586,
        "lng": 29.6943
    },
    {
        "stationCod": 68182,
        "name": "LEVUBU",
        "status": "enabled",
        "type": "automatic",
        "city": "LEVUBU",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -23.0943,
        "lng": 30.2863
    },
    {
        "stationCod": 68183,
        "name": "THOHOYANDOU AWS",
        "status": "enabled",
        "type": "automatic",
        "city": "THOHOYANDOU AWS",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -23.0797,
        "lng": 30.3838
    },
    {
        "stationCod": 68187,
        "name": "GIYANI",
        "status": "enabled",
        "type": "automatic",
        "city": "GIYANI",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -23.3142,
        "lng": 30.6849
    },
    {
        "stationCod": 68184,
        "name": "TSHIVHASIE TEA VENDA",
        "status": "enabled",
        "type": "automatic",
        "city": "TSHIVHASIE TEA VENDA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -22.9607,
        "lng": 30.3545
    },
    {
        "stationCod": 68189,
        "name": "TSHANOWA PRIMARY SCHOOL",
        "status": "enabled",
        "type": "automatic",
        "city": "TSHANOWA PRIMARY SCHOOL",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -22.9352,
        "lng": 30.3668
    },
    {
        "stationCod": 68186,
        "name": "MUKUMBANI TEA ESTATE - VENDA",
        "status": "enabled",
        "type": "automatic",
        "city": "MUKUMBANI TEA ESTATE - VENDA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -22.9169,
        "lng": 30.4055
    },
    {
        "stationCod": 68192,
        "name": "THOHOYANDOU WO",
        "status": "enabled",
        "type": "automatic",
        "city": "THOHOYANDOU WO",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -22.9845,
        "lng": 30.4583
    },
    {
        "stationCod": 68196,
        "name": "PUNDA MARIA",
        "status": "enabled",
        "type": "automatic",
        "city": "PUNDA MARIA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -22.692,
        "lng": 31.0159
    },
    {
        "stationCod": 68177,
        "name": "MANKWENG",
        "status": "enabled",
        "type": "automatic",
        "city": "MANKWENG",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -23.8864,
        "lng": 29.7432
    },
    {
        "stationCod": 68172,
        "name": "VENETIA MINE",
        "status": "enabled",
        "type": "automatic",
        "city": "VENETIA MINE",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -22.4517,
        "lng": 29.3315
    },
    {
        "stationCod": 68845,
        "name": "BIRD ISLAND",
        "status": "enabled",
        "type": "automatic",
        "city": "BIRD ISLAND",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -33.8388,
        "lng": 26.2861
    },
    {
        "stationCod": 68176,
        "name": "MARA",
        "status": "enabled",
        "type": "automatic",
        "city": "MARA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -23.1443,
        "lng": 29.557
    },
    {
        "stationCod": 68296,
        "name": "SKUKUZA",
        "status": "enabled",
        "type": "automatic",
        "city": "SKUKUZA",
        "country": "ZA",
        "entity": "afrigis",
        "lat": -24.9926,
        "lng": 31.588
    }
]